## Numpy Basics


In [3]:
import numpy as np

In [13]:
a = np.arange(1, 13)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [6]:
b = np.arange(1, 10, 2.5)
b

array([1. , 3.5, 6. , 8.5])

In [55]:
a = a.reshape(4, 3) #returns a new array of the given size
print(a)

ValueError: cannot reshape array of size 30 into shape (4,3)

In [17]:
c = np.array([1, 2 , 3])
c

array([1, 2, 3])

In [18]:
e = np.array([(1,20), (3,20)])
e

array([[ 1, 20],
       [ 3, 20]])

In [26]:
f = np.array([-1, 0, 100], dtype="int8")
f

array([ -1,   0, 100], dtype=int8)

In [27]:
f*2

array([ -2,   0, -56], dtype=int8)

In [29]:
f = f.astype('float32')
f

array([ -1.,   0., 100.], dtype=float32)

In [31]:
b = a.reshape(3, 4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
b[0, 1:]

array([2, 3, 4])

In [33]:
b[:, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [34]:
b[1:, 2:]

array([[ 7,  8],
       [11, 12]])

## 3D Tensors

In [35]:
c = np.arange(24)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [36]:
c = c.reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [37]:
c[1,1,1]

17

In [38]:
c[0, :, :]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## Vectorize Map

In [39]:
a = np.arange(1, 6)
a

array([1, 2, 3, 4, 5])

In [40]:
a*2

array([ 2,  4,  6,  8, 10])

This behavior of numpy of applying mathematical operations on each element of an array is called vectorization.

In [41]:
a< 3

array([ True,  True, False, False, False])

In [43]:
b = np.arange(5, 10)
b

array([5, 6, 7, 8, 9])

In [44]:
a+b 

array([ 6,  8, 10, 12, 14])

In [45]:
a*b

array([ 5, 12, 21, 32, 45])

## Dot and Matrix Multiplication

In [46]:
a.dot(b) #dot product gives scalar answer

115

In [48]:
a.shape

(5,)

In [49]:
c.shape

(2, 3, 4)

In [50]:
b.T #b is a vector

array([5, 6, 7, 8, 9])

In [51]:
c.T # C is a tensor

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

## Filtering(Masking)

In [52]:
a = np.arange(30)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [53]:
a > 15

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [54]:
a[a>15] #filtered, always returns a vector

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [56]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [57]:
b = a.reshape(6,5)

In [58]:
b.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [60]:
c = a[:15]
c


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [61]:
c.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [63]:
a[0] = 100
a

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])

In [64]:
b

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29]])

In [65]:
#Updating a also updates b and c

In [66]:
#Masking returns a new array.

## Reshaping

In [68]:
b = a.reshape(6, -1)
b

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29]])

In [70]:
# Numpy guesses the number for -1. But two -1's cannot be given 
#because it is ambigioius

In [71]:
b.flatten() #Returns a vector

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])

## Special Arrays

In [73]:
np.zeros(5) #default is float, change using dtype parameter

array([0., 0., 0., 0., 0.])

In [74]:
np.zeros((5,4), dtype="int8") #if given matrix should be given as tuple

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [75]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [76]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [77]:
np.eye(3) #identity matrix but flexible because can also create non square matrices

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [78]:
np.identity(3) #strict identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [79]:
np.linspace(1, 5, 9) #3rd parameter divides the entire array into that many parts.

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [80]:
np.linspace(1, 110, 5)

array([  1.  ,  28.25,  55.5 ,  82.75, 110.  ])

## Analysis

In [81]:
a.sum() #Sums everything up

535

In [82]:
a.shape

(30,)

In [83]:
b = b.reshape(5,6)
b

array([[100,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29]])

In [84]:
b.sum(axis =0) #0 Axis goes through the rows, 1 goes through columns

array([160,  65,  70,  75,  80,  85])

In [85]:
b.sum(axis =1)

array([115,  51,  87, 123, 159])

In [86]:
#For tensors the axis is 0=trough the martices , 1=trough rows, 2=through columns

In [87]:
c = np.arange(24).reshape(4,3,2)
c

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [94]:
c.sum(axis=2)

array([[ 1,  5,  9],
       [13, 17, 21],
       [25, 29, 33],
       [37, 41, 45]])

In [95]:
b.max()

100

In [96]:
b.max(axis=0)

array([100,  25,  26,  27,  28,  29])

In [97]:
b.mean()

17.833333333333332

In [98]:
b.mean(axis=0)

array([32., 13., 14., 15., 16., 17.])

In [100]:
np.median(b, axis=0)

array([18., 13., 14., 15., 16., 17.])

In [101]:
np.std(b)

17.33413459686472

## Random

In [102]:
np.random.rand(4, 5)

array([[0.25771677, 0.24175662, 0.53843116, 0.33717435, 0.18190241],
       [0.89985833, 0.16524778, 0.62864309, 0.04296259, 0.86082042],
       [0.0456013 , 0.99503197, 0.21603959, 0.90721893, 0.50982176],
       [0.42956189, 0.15863966, 0.08705673, 0.86194601, 0.34623028]])

In [103]:
# to change range we have to manually do math operarations.

In [104]:
90 + np.random.rand(4, 5)*10

array([[94.10353624, 92.28828199, 90.74770342, 99.88756964, 94.06458125],
       [93.58345212, 94.20995742, 99.92796721, 97.87333807, 98.40601717],
       [92.10436741, 96.81834771, 98.18189923, 94.95213437, 96.10948576],
       [92.27484016, 90.06029438, 90.6645433 , 92.48269813, 98.36149391]])

In [105]:
np.random.randint(50, 60 ,5) # 50-60 is range in int

array([58, 57, 55, 58, 53])

In [106]:
np.random.seed(32)
np.random.rand()

0.8588892672930397

In [109]:
mu = 100
sigma = 15
np.random.normal(mu, sigma, 10)

array([ 81.14053587, 101.97284933,  96.87034379,  98.68199581,
       111.35570112,  83.02022272, 110.46103947, 115.13315755,
        98.91683318,  68.95664955])

In [113]:
#! pip install matplotlib

## Sorting

In [133]:
d = np.random.randint(5, 25, 12).reshape(3, 4)
d

array([[ 5, 12,  5, 21],
       [ 8, 23, 13,  7],
       [10, 13, 19, 23]])

In [129]:
d.sort()
d

array([[ 7, 13, 15, 22],
       [ 9, 13, 14, 23],
       [ 5,  9, 22, 23]])

In [130]:
d = d.flatten()
d

array([ 7, 13, 15, 22,  9, 13, 14, 23,  5,  9, 22, 23])

In [131]:
d.sort()

In [132]:
d.reshape(3,4)

array([[ 5,  7,  9,  9],
       [13, 13, 14, 15],
       [22, 22, 23, 23]])

In [134]:
d.sort(axis=0)

In [135]:
d

array([[ 5, 12,  5,  7],
       [ 8, 13, 13, 21],
       [10, 23, 19, 23]])